/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Test_brokerRouteImport } from './routes/test_broker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolveIndexRouteImport } from './routes/solve/index'
import { Route as SolveActivityTaskIdIndexRouteImport } from './routes/solve/$activityTaskId/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTasksIndexRouteImport } from './routes/admin/tasks/index'
import { Route as AdminActivitiesIndexRouteImport } from './routes/admin/activities/index'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as AdminTasksNewRouteImport } from './routes/admin/tasks/new'
import { Route as AdminActivitiesNewRouteImport } from './routes/admin/activities/new'
import { Route as AdminTasksTaskIdRouteRouteImport } from './routes/admin/tasks/$taskId/route'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminTasksTaskIdIndexRouteImport } from './routes/admin/tasks/$taskId/index'
import { Route as AdminActivitiesActivityIdIndexRouteImport } from './routes/admin/activities/$activityId/index'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'
import { Route as AdminTasksTaskIdEditRouteImport } from './routes/admin/tasks/$taskId/edit'
import { Route as AdminActivitiesActivityIdEditRouteImport } from './routes/admin/activities/$activityId/edit'
import { Route as AdminActivitiesActivityIdTasksAddRouteImport } from './routes/admin/activities/$activityId/tasks/add'
import { Route as AdminActivitiesActivityIdTasksActivityTaskIdEditRouteImport } from './routes/admin/activities/$activityId/tasks/$activityTaskId/edit'

const Test_brokerRoute = Test_brokerRouteImport.update({
  id: '/test_broker',
  path: '/test_broker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolveIndexRoute = SolveIndexRouteImport.update({
  id: '/solve/',
  path: '/solve/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolveActivityTaskIdIndexRoute =
  SolveActivityTaskIdIndexRouteImport.update({
    id: '/solve/$activityTaskId/',
    path: '/solve/$activityTaskId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/admin/tasks/',
  path: '/admin/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesIndexRoute = AdminActivitiesIndexRouteImport.update({
  id: '/admin/activities/',
  path: '/admin/activities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/admin/tasks/new',
  path: '/admin/tasks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivitiesNewRoute = AdminActivitiesNewRouteImport.update({
  id: '/admin/activities/new',
  path: '/admin/activities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksTaskIdRouteRoute = AdminTasksTaskIdRouteRouteImport.update({
  id: '/admin/tasks/$taskId',
  path: '/admin/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/admin/users/$userId/',
  path: '/admin/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksTaskIdIndexRoute = AdminTasksTaskIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTasksTaskIdRouteRoute,
} as any)
const AdminActivitiesActivityIdIndexRoute =
  AdminActivitiesActivityIdIndexRouteImport.update({
    id: '/admin/activities/$activityId/',
    path: '/admin/activities/$activityId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/admin/users/$userId/edit',
  path: '/admin/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTasksTaskIdEditRoute = AdminTasksTaskIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminTasksTaskIdRouteRoute,
} as any)
const AdminActivitiesActivityIdEditRoute =
  AdminActivitiesActivityIdEditRouteImport.update({
    id: '/admin/activities/$activityId/edit',
    path: '/admin/activities/$activityId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminActivitiesActivityIdTasksAddRoute =
  AdminActivitiesActivityIdTasksAddRouteImport.update({
    id: '/admin/activities/$activityId/tasks/add',
    path: '/admin/activities/$activityId/tasks/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminActivitiesActivityIdTasksActivityTaskIdEditRoute =
  AdminActivitiesActivityIdTasksActivityTaskIdEditRouteImport.update({
    id: '/admin/activities/$activityId/tasks/$activityTaskId/edit',
    path: '/admin/activities/$activityId/tasks/$activityTaskId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/test_broker': typeof Test_brokerRoute
  '/solve/': typeof SolveIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRouteRouteWithChildren
  '/admin/activities/new': typeof AdminActivitiesNewRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/activities/': typeof AdminActivitiesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/solve/$activityTaskId/': typeof SolveActivityTaskIdIndexRoute
  '/admin/activities/$activityId/edit': typeof AdminActivitiesActivityIdEditRoute
  '/admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/activities/$activityId/': typeof AdminActivitiesActivityIdIndexRoute
  '/admin/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/activities/$activityId/tasks/add': typeof AdminActivitiesActivityIdTasksAddRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/edit': typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/test_broker': typeof Test_brokerRoute
  '/solve': typeof SolveIndexRoute
  '/admin/activities/new': typeof AdminActivitiesNewRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/activities': typeof AdminActivitiesIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/solve/$activityTaskId': typeof SolveActivityTaskIdIndexRoute
  '/admin/activities/$activityId/edit': typeof AdminActivitiesActivityIdEditRoute
  '/admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/admin/activities/$activityId/tasks/add': typeof AdminActivitiesActivityIdTasksAddRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/edit': typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/test_broker': typeof Test_brokerRoute
  '/solve/': typeof SolveIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRouteRouteWithChildren
  '/admin/activities/new': typeof AdminActivitiesNewRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/activities/': typeof AdminActivitiesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/solve/$activityTaskId/': typeof SolveActivityTaskIdIndexRoute
  '/admin/activities/$activityId/edit': typeof AdminActivitiesActivityIdEditRoute
  '/admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/activities/$activityId/': typeof AdminActivitiesActivityIdIndexRoute
  '/admin/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/activities/$activityId/tasks/add': typeof AdminActivitiesActivityIdTasksAddRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/edit': typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/test_broker'
    | '/solve/'
    | '/admin/tasks/$taskId'
    | '/admin/activities/new'
    | '/admin/tasks/new'
    | '/admin/users/new'
    | '/admin/activities/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/solve/$activityTaskId/'
    | '/admin/activities/$activityId/edit'
    | '/admin/tasks/$taskId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/activities/$activityId/'
    | '/admin/tasks/$taskId/'
    | '/admin/users/$userId/'
    | '/admin/activities/$activityId/tasks/add'
    | '/admin/activities/$activityId/tasks/$activityTaskId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/test_broker'
    | '/solve'
    | '/admin/activities/new'
    | '/admin/tasks/new'
    | '/admin/users/new'
    | '/admin/activities'
    | '/admin/tasks'
    | '/admin/users'
    | '/solve/$activityTaskId'
    | '/admin/activities/$activityId/edit'
    | '/admin/tasks/$taskId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/activities/$activityId'
    | '/admin/tasks/$taskId'
    | '/admin/users/$userId'
    | '/admin/activities/$activityId/tasks/add'
    | '/admin/activities/$activityId/tasks/$activityTaskId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/test_broker'
    | '/solve/'
    | '/admin/tasks/$taskId'
    | '/admin/activities/new'
    | '/admin/tasks/new'
    | '/admin/users/new'
    | '/admin/activities/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/solve/$activityTaskId/'
    | '/admin/activities/$activityId/edit'
    | '/admin/tasks/$taskId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/activities/$activityId/'
    | '/admin/tasks/$taskId/'
    | '/admin/users/$userId/'
    | '/admin/activities/$activityId/tasks/add'
    | '/admin/activities/$activityId/tasks/$activityTaskId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  Test_brokerRoute: typeof Test_brokerRoute
  SolveIndexRoute: typeof SolveIndexRoute
  AdminTasksTaskIdRouteRoute: typeof AdminTasksTaskIdRouteRouteWithChildren
  AdminActivitiesNewRoute: typeof AdminActivitiesNewRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminActivitiesIndexRoute: typeof AdminActivitiesIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  SolveActivityTaskIdIndexRoute: typeof SolveActivityTaskIdIndexRoute
  AdminActivitiesActivityIdEditRoute: typeof AdminActivitiesActivityIdEditRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminActivitiesActivityIdIndexRoute: typeof AdminActivitiesActivityIdIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
  AdminActivitiesActivityIdTasksAddRoute: typeof AdminActivitiesActivityIdTasksAddRoute
  AdminActivitiesActivityIdTasksActivityTaskIdEditRoute: typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test_broker': {
      id: '/test_broker'
      path: '/test_broker'
      fullPath: '/test_broker'
      preLoaderRoute: typeof Test_brokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solve/': {
      id: '/solve/'
      path: '/solve'
      fullPath: '/solve/'
      preLoaderRoute: typeof SolveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solve/$activityTaskId/': {
      id: '/solve/$activityTaskId/'
      path: '/solve/$activityTaskId'
      fullPath: '/solve/$activityTaskId/'
      preLoaderRoute: typeof SolveActivityTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/admin/tasks'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities/': {
      id: '/admin/activities/'
      path: '/admin/activities'
      fullPath: '/admin/activities/'
      preLoaderRoute: typeof AdminActivitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/admin/tasks/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities/new': {
      id: '/admin/activities/new'
      path: '/admin/activities/new'
      fullPath: '/admin/activities/new'
      preLoaderRoute: typeof AdminActivitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/$taskId': {
      id: '/admin/tasks/$taskId'
      path: '/admin/tasks/$taskId'
      fullPath: '/admin/tasks/$taskId'
      preLoaderRoute: typeof AdminTasksTaskIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/$taskId/': {
      id: '/admin/tasks/$taskId/'
      path: '/'
      fullPath: '/admin/tasks/$taskId/'
      preLoaderRoute: typeof AdminTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminTasksTaskIdRouteRoute
    }
    '/admin/activities/$activityId/': {
      id: '/admin/activities/$activityId/'
      path: '/admin/activities/$activityId'
      fullPath: '/admin/activities/$activityId/'
      preLoaderRoute: typeof AdminActivitiesActivityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/admin/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tasks/$taskId/edit': {
      id: '/admin/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/admin/tasks/$taskId/edit'
      preLoaderRoute: typeof AdminTasksTaskIdEditRouteImport
      parentRoute: typeof AdminTasksTaskIdRouteRoute
    }
    '/admin/activities/$activityId/edit': {
      id: '/admin/activities/$activityId/edit'
      path: '/admin/activities/$activityId/edit'
      fullPath: '/admin/activities/$activityId/edit'
      preLoaderRoute: typeof AdminActivitiesActivityIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities/$activityId/tasks/add': {
      id: '/admin/activities/$activityId/tasks/add'
      path: '/admin/activities/$activityId/tasks/add'
      fullPath: '/admin/activities/$activityId/tasks/add'
      preLoaderRoute: typeof AdminActivitiesActivityIdTasksAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activities/$activityId/tasks/$activityTaskId/edit': {
      id: '/admin/activities/$activityId/tasks/$activityTaskId/edit'
      path: '/admin/activities/$activityId/tasks/$activityTaskId/edit'
      fullPath: '/admin/activities/$activityId/tasks/$activityTaskId/edit'
      preLoaderRoute: typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminTasksTaskIdRouteRouteChildren {
  AdminTasksTaskIdEditRoute: typeof AdminTasksTaskIdEditRoute
  AdminTasksTaskIdIndexRoute: typeof AdminTasksTaskIdIndexRoute
}

const AdminTasksTaskIdRouteRouteChildren: AdminTasksTaskIdRouteRouteChildren = {
  AdminTasksTaskIdEditRoute: AdminTasksTaskIdEditRoute,
  AdminTasksTaskIdIndexRoute: AdminTasksTaskIdIndexRoute,
}

const AdminTasksTaskIdRouteRouteWithChildren =
  AdminTasksTaskIdRouteRoute._addFileChildren(
    AdminTasksTaskIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  Test_brokerRoute: Test_brokerRoute,
  SolveIndexRoute: SolveIndexRoute,
  AdminTasksTaskIdRouteRoute: AdminTasksTaskIdRouteRouteWithChildren,
  AdminActivitiesNewRoute: AdminActivitiesNewRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminActivitiesIndexRoute: AdminActivitiesIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  SolveActivityTaskIdIndexRoute: SolveActivityTaskIdIndexRoute,
  AdminActivitiesActivityIdEditRoute: AdminActivitiesActivityIdEditRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminActivitiesActivityIdIndexRoute: AdminActivitiesActivityIdIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
  AdminActivitiesActivityIdTasksAddRoute:
    AdminActivitiesActivityIdTasksAddRoute,
  AdminActivitiesActivityIdTasksActivityTaskIdEditRoute:
    AdminActivitiesActivityIdTasksActivityTaskIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
