"""Progress on student specific tasks

Revision ID: 0b7a29bd5b5e
Revises: 9850910e331e
Create Date: 2026-03-19 10:11:04.706309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7a29bd5b5e'
down_revision = '9850910e331e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_mode', sa.String(), server_default='all', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.drop_column('student_mode')

    # ### end Alembic commands ###
