"""add assignment_id to user_started_tasks

Revision ID: 3e6badb02a4c
Revises: 3f8c2a9b1e4d
Create Date: 2026-06-15 17:34:39.691374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e6badb02a4c'
down_revision = '3f8c2a9b1e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['assignment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('assignment_id')

    op.create_table('action_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('app_mode', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('action_logs_pkey'))
    )
    # ### end Alembic commands ###
