"""Added preview and instructions to ActivityTask, removed description

Revision ID: 529dd6fd9a54
Revises: b523bb1ddca1
Create Date: 2026-03-05 09:30:24.618427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529dd6fd9a54'
down_revision = 'b523bb1ddca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('instructions')
        batch_op.drop_column('preview')

    # ### end Alembic commands ###
