"""added user_started_task and activity_task relation

Revision ID: 65c5e16959ea
Revises: 02f0d28be916
Create Date: 2026-02-23 15:55:13.179444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c5e16959ea'
down_revision = '02f0d28be916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_task_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('user_started_tasks_activity_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_started_tasks_task_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'activity_tasks', ['activity_task_id'], ['id'])
        batch_op.drop_column('task_id')
        batch_op.drop_column('activity_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_started_tasks_task_id_fkey'), 'tasks', ['task_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('user_started_tasks_activity_id_fkey'), 'activities', ['activity_id'], ['id'])
        batch_op.drop_column('activity_task_id')

    # ### end Alembic commands ###
