"""added difficulty to activity_task

Revision ID: 9850910e331e
Revises: 529dd6fd9a54
Create Date: 2026-03-11 19:50:00.691916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9850910e331e'
down_revision = '529dd6fd9a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
