"""Added is_logged and allows_robot to ActivityTask

Revision ID: ad2c77523752
Revises: 
Create Date: 2026-02-18 14:18:31.976837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2c77523752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_logged', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('allows_robot', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_tasks', schema=None) as batch_op:
        batch_op.drop_column('allows_robot')
        batch_op.drop_column('is_logged')

    # ### end Alembic commands ###
