"""add update user_started_logs table

Revision ID: b523bb1ddca1
Revises: 65c5e16959ea
Create Date: 2026-02-26 12:11:34.432270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b523bb1ddca1'
down_revision = '65c5e16959ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finished', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['started_by', 'activity_task_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_finished')

    # ### end Alembic commands ###
